apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: flow-emulator-v1
  namespace: flow
  labels:
    app: flow-emulator
    env: production
    owner: Kan
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "autoincrement"
spec:
  rules:
  - host: emulator-grpc.onflow.org
    http:
      paths:
        - backend:
            serviceName: flow-emulator-v1
            servicePort: grpc
              rules:
  - host: emulator-http.onflow.org
    http:
      paths:
        - backend:
            serviceName: flow-emulator-v1
            servicePort: http
---

apiVersion: v1
kind: Service

metadata:
  name: flow-emulator-v1
  namespace: flow

  labels:
    app: flow-emulator
    env: production
    owner: Kan
    version: v1

spec:
  type: ClusterIP
  selector:
    app: flow-emulator
    env: production
    version: v1

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http # reference to the name of the port in your container config
    - name: grpc
      protocol: TCP
      port: 3569
      targetPort: grpc # reference to the name of the port in your container config
